default:
  controller: Main
  action: home

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

dashboard:
  controller: Stat
  action: dashboard

profile:
  controller: Account
  action: profile

other:
  controller: Account
  action: other

user-list:
  controller: User
  action: userList